version: '3'

services:

  frontend:
    build: 
      context: Dockerfile             
    depends_on:
      - backend-services
      - api-services
    deploy:
      mode: replicated
      # Add more replicas when i need more availibity... right now 3 is completely fine
      replicas: 3
    restart: always
    ports:
      - 5001:8080

  backend:
    build: 
      context: Dockerfile 
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    ports:
      - 5002:8081

  api:
    build: 
      context: Dockerfile 
    depends_on: 
      - db
    deploy:
      mode:  replicated
      # Add more replicas when i need more availibity... right now 3 is completely fine
      replicas: 3
    
    restart: always
    ports:
      - 5003:8082

  nginx:
    build:
      context: Dockerfile 
    depends_on:
      - api
      - backend
      - frontend 
    restart: always
    ports:
      - 443:443

  postgres:
    image: db
    expose:
    - 5432
    environment:
      POSTGRES_USER: "utilitybot"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "databasename"
    
  db:
    # Match db version on our server
    image: postgres:13
      
