version: '3.7'

services:

  frontend-services:
    build: 

      context: .
      image: frontend-services:1.0

    depends_on:
      - ./backend:/src/static/backend

    volumes:
      - ./frontend:/usr/src/frontend

    restart: always

    ports:
      - 8080:8080

  backend-services:

    build: 

      context: .
      image: backend-services:1.0

    depends_on:
      - ./frontend:/src/static/frontend

    volumes:
      - ./backend:/usr/src/backend

    restart: always

    ports:
      - 8081:8081


  api-services:
    
    build: 

      context: .
      image: api-service:1.0

    restart: always

    volumes: 
      - ./api:/usr/src/api

    ports:
    - 8082:8082
    
    depends_on:
      - frontend-services
      - db

    
  db:
    image: postgres

    expose:
    - 5432

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_dB}


