version: '3'

services:

  frontend:
    build: 
      context: ./website/src/frontend/Dockerfile
    depends_on:
      - backend-services
      - api-services
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    volumes:
      - frontend
    restart: always
    ports:
      - 5001:8080

  backend:
    build: 
      context: ./website/src/backend/Dockerfile
    depends_on:
      - db
    volumes:
      - backend
    restart: always
    ports:
      - 5002:8081

  api:
    build: 
      context: .
    depends_on: 
      - db
    deploy:
      mode:  replicated
      replicas: 3
      endpoint_mode: dnsrr
    volumes: .
    restart: always
    ports:
      - 5003:8082

  nginx:
    build:
      context: .
    depends_on:
      - api
      - backend
      - frontend #
    restart: always
    ports:
      - 443:443

  postgres:
    image: db
    expose:
    - 5432
    environment:
      POSTGRES_USER: "utilitybot"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "databasename"
    
  db:
    image: postgres:13
      
