version: '3'

services:

  frontend-services:
    build: 
      context: .
      image: frontend-services
    depends_on:
      - backend-services
      - api-services
    volumes:
      - ./frontend:/usr/src/frontend
    restart: always
    ports:
      - 5001:8080

  backend-services:
    build: 
      context: .
      image: backend-services
    depends_on:
      - frontend-services
    volumes:
      - ./backend:/usr/src/backend
    restart: always
    ports:
      - 5001:8081

  api-services:
    build: 
      context: .
      image: api-service
    restart: always
    volumes: 
      - ./api:/usr/src/api
    ports:
    - 5001:8082

    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_HOST: ${POSTGRES_HOST}
      - POSTGRES_PORT: ${POSTGRES_PORT}

    depends_on:
      - frontend-services
      - postgres


  postgres:
    image: postgres:latest

    expose:
    - 5432

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
