version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.6.0
    steps:
      - checkout
      - run:
          name: Install pypi Dependencies
          command: |
            echo 'export PATH=~$PATH~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip3 install -r requirements.txt