version: '3'

services:
  frontend-services:
    image: frontend-services:1.0

    build: 
      context: ./static/frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend:/var/www/app

    ports:
      - 5000:8080

  backend-services:

    build: 
      context: ./static/backend
      dockerfile: Dockerfile
    
    volumes:
      - ./backend:/src/static/backend

    ports:
      - 5000:8081

  
  api-services:

    depends_on:
       - postgres
      
    environnment:
      POSTGRES_HOST: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_PORT: ""

    build: 
      context: ./static/api
      dockerfile: Dockerfile

    volumes: 
      - ./api:/src/static/api

    ports:
     - 5000:8082

  postgres:
    image: postgres
  
    
  
    