version: '3'

services:
  frontend-service:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8080:8080

services:
  backend-services:
    build: ./backend
    volumes: 
      - ./backend:/usr/src/app
    ports:
      8081:8081
    depends_on:
      - frontend-service