version: '3'

services:

  frontend-services:

    build: ./frontend
      
    depends_on:
      - ./backend:/src/static/backend

    volumes:
      - ./frontend:/usr/src/frontend

    ports:
      - 8080:8080

  backend-services:
    build: ./src/static/backend
      
    depends_on:
      - ./frontend:/src/static/frontend

    volumes:
      - ./backend:/usr/src/backend

    ports:
      - 8081:8081


  api-service:

    build: 
      - ./api
    
    environnment:
      - POSTGRES_HOST: ""
      - POSTGRES_USER: ""
      - POSTGRES_PASSWORD: ""

    volumes: 
      - ./api:/usr/src/api

    ports:
      - 8082:8082

    depends_on:
    -  frontend-services
    - db

  db:
    image: postgres