version: '3'

services:
  frontend-services:
    image: frontend-services:1.0
    build: 
      context: ./static/frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/var/www/app
    ports:
      - 8080:8080

  backend-services:
    image: backend-services:1.0
    build: ./backend
    volumes:
      - ./backend:/src/static/backend
    ports:
      - 8080:8081

  api-services:
    image: api-services:1.0
    environnment:
      POSTGRES_HOST: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""

    build: ./api
    volumes: 
      - ./api:/src/static/api
    ports:
      - 8082:8082

    
    
    