version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/src/static/frontend
    ports:
      - 8080:8080

  website:
    image: 
      volumes:
        ./backend:/src/static/backend