version: '3'

services:

  frontend-services:
    build: 
      image: frontend-services:1.0

    depends_on:
      - ./backend:/src/static/backend
      
    volumes:
      - ./frontend:/usr/src/frontend

    ports:
      - 8080:8080

  backend-services:
    build: 
      image: backend-services:1.0

    depends_on:
      - ./frontend:/src/static/frontend

    volumes:
      - ./backend:/usr/src/backend

    ports:
      - 8081:8081


  api-service:
    build: 
      image: api-service:1.0

    environnment:
      - POSTGRES_HOST: ""
      - POSTGRES_USER: ""
      - POSTGRES_PASSWORD: ""

    volumes: 
      - ./api:/usr/src/api
    ports:

      - 8082:8082
    depends_on:
    -  frontend-services
    - db

  db:
    image: postgres