name: Build
on:
  push:
    branches:
    - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: Pull code
        uses: actions/checkout@main


      - name: Install deps for bot 
        run: | 
          pip3 install requirements.txt
          python bot.py


      