name: contributors

on:
  push:
    branches:
      - dev

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cjdenio/contributor_list@master
        with:
          commit_message: Update contributors list
          max_contributors: 20