name: Pull
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: 🔐 Login to Github Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u Matt-Gleich --password-stdin
      - name: 🏗️ Building Images
        run: |
          docker build -t docker.pkg.github.com/discordutilitybot/utilitybot/utilitybot 
          
      - name: 🚀 Pushing Images to Github Packages
        run: |
          docker push docker.pkg.github.com/discordutilitybot/utilitybot/utilitybot
          docker push docker.pkg.github.com/matt-gleich/dockerfiles/docker-and-python
