name: pull

on:
  push:
    branches:
      - dev

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
    
      - name: Python checkout
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      
      - name: Pull docker image
        run: |
          docker pull docker.pkg.github.com/discordutilitybot/utilitybot/utilitybot:1.1
